server.port: 8080

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/academia?useTimezone=true&serverTimezone=UTC&useLegacyDate
        username: postgres
        password: admin@123

    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      properties:
        hibernate.format_sql: true

logging:
  level:
    org:
      hibernate:
        type: trace